version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
      nodejs: 12
      python: 3.7
  pre_build:
    commands:
      - "cd infrastructure"
      - 'npm install -g aws-cdk'
      - 'pip install --upgrade pip'
      - 'pip install -r requirements.txt'
  build:
    commands:
      - 'cdk deploy "*" --context stack=$ENV --require-approval never'
cache:
  paths:
  - '/~/.docker-cache/**/*'
  - '~/.cache/**/*'
  - '~/.npm/**/*'
